
services:
  postgres:
    image: postgres:15-alpine
    container_name: codestream_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Codemashido
      POSTGRES_PASSWORD: Google74192
      POSTGRES_DB: codestream
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: codestream_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
